name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "helm/**"
      - "**/*.md"

permissions:
  contents: write

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: go build -o main .

      - name: Test
        run: go test ./...

      - name: Set image tag
        id: vars
        run: |
          TAG="${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: karray005
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
         tags: |
        karray005/go-web-app:${{ steps.vars.outputs.tag }}
        karray005/go-web-app:latest


      - name: Update Helm values.yaml
        run: |
          sed -i "s/^  tag: .*/  tag: ${{ steps.vars.outputs.tag }}/" helm/go-web-app/values.yaml

      - name: Commit and push Helm update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/go-web-app/values.yaml
          git commit -m "ci: bump image tag" || echo "No changes"
          git push
